-- Supabase SQL Editor에서 한 번 실행하세요.
create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  result jsonb not null,
  created_at timestamptz not null default now(),
  constraint lotto_draws_result_is_object check (jsonb_typeof(result) = 'object')
);

create index if not exists lotto_draws_created_at_idx
  on public.lotto_draws (created_at desc);

-- 브라우저에서는 테이블에 직접 접근하지 않습니다.
-- Vercel의 서버 API만 service_role 키로 접근하므로 RLS는 켜 둡니다.
alter table public.lotto_draws enable row level security;
